version: '3.8'
services:
  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/var/www/app
    command: bash -c "npm install && npm run build"
  backend:
    build: ./docker/backend
    volumes:
      - ./backend:/var/www/app
  nginx:
    image: nginx 
    restart: always
    ports:
      - 80:80 
      - 443:443
      - 8000:8000
    volumes:
      - ./frontend/build:/var/www/app
      - ./docker/letsencrypt:/etc/letsencrypt
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  certbot:
    image: certbot/certbot
    volumes:
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"
    volumes:
      - ./docker/letsencrypt:/etc/letsencrypt
      - ./fronten/build:/var/www/app
    command: ["--version"]
  db:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - app-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    environment:
        MYSQL_USERNAME: ${DB_USERNAME}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        PMA_HOST: ${DB_HOST}
volumes:
  app-data:
