version: '3.8'
services:
  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/var/www/app
    command: bash -c "npm install && npm run build"
  backend:
    build: ./docker/backend
    volumes:
      - ./backend:/var/www/app
  nginx:
    image: nginx 
    restart: always
    ports:
      - 80:80 
      - 443:443
      - 8000:8000
    volumes:
      - ./frontend/build:/var/www/app
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    environment:
        MYSQL_USERNAME: ${DB_USERNAME}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        PMA_HOST: ${DB_HOST}
volumes:
  app-data:
